apiVersion: batch/v1
kind: Job
metadata:
  generateName: stt-app-db-migrate-job-
spec:
  template:
    metadata:
      labels:
        app: stt-app
    spec:
      restartPolicy: Never
      containers:
        - name: stt-app-migration-container
          image: us.gcr.io/sql-connect-test-app/app:v12
          imagePullPolicy: Always
          command:
            - bin/rails
            - db:migrate
          env:
            - name: PSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rails-web-credentials
                  key: db_name
            - name: PSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rails-web-credentials
                  key: db_user
            - name: PSQL_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: rails-web-credentials
                  key: db_password
            # I have to use connection via private IP because extra container
            # with cloud_sql_proxy will broke job. SSL is turned off as well, but
            # can be enabled with custom certs. Main app will use cloud_sql_proxy
            - name: PSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: rails-web-credentials-for-migrate-job
                  key: db_host
