kind: Service
apiVersion: v1
metadata:
  name: rails-web-service
spec:
  selector:
    app: stt-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3000