require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/writers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Writer. As you add validations to Writer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Writer.create! valid_attributes
      get writers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      writer = Writer.create! valid_attributes
      get writer_url(writer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_writer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      writer = Writer.create! valid_attributes
      get edit_writer_url(writer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Writer" do
        expect {
          post writers_url, params: { writer: valid_attributes }
        }.to change(Writer, :count).by(1)
      end

      it "redirects to the created writer" do
        post writers_url, params: { writer: valid_attributes }
        expect(response).to redirect_to(writer_url(Writer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Writer" do
        expect {
          post writers_url, params: { writer: invalid_attributes }
        }.to change(Writer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post writers_url, params: { writer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested writer" do
        writer = Writer.create! valid_attributes
        patch writer_url(writer), params: { writer: new_attributes }
        writer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the writer" do
        writer = Writer.create! valid_attributes
        patch writer_url(writer), params: { writer: new_attributes }
        writer.reload
        expect(response).to redirect_to(writer_url(writer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        writer = Writer.create! valid_attributes
        patch writer_url(writer), params: { writer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested writer" do
      writer = Writer.create! valid_attributes
      expect {
        delete writer_url(writer)
      }.to change(Writer, :count).by(-1)
    end

    it "redirects to the writers list" do
      writer = Writer.create! valid_attributes
      delete writer_url(writer)
      expect(response).to redirect_to(writers_url)
    end
  end
end
